export const pagesRoutes = [
  ["v-8daa1a0e","/",{"t":"首页"},["/index.html","/README.md"]],
  ["v-621c6c82","/components/introduction.html",{"t":"bitsail-components"},["/components/introduction","/components/introduction.md"]],
  ["v-4136df22","/connectors/introduction.html",{"t":"BitSail 连接器"},["/connectors/introduction","/connectors/introduction.md"]],
  ["v-285a52d1","/start/config.html",{"t":"任务配置说明"},["/start/config","/start/config.md"]],
  ["v-4a4410ae","/start/contributing.html",{"t":"贡献者指引"},["/start/contributing","/start/contributing.md"]],
  ["v-47d1c82e","/start/deployment.html",{"t":"部署指南"},["/start/deployment","/start/deployment.md"]],
  ["v-56dddcd4","/start/env_setup.html",{"t":"环境配置"},["/start/env_setup","/start/env_setup.md"]],
  ["v-2d0ad528","/zh/",{"t":"首页"},["/zh/index.html","/zh/README.md"]],
  ["v-227d8b56","/zh_backup/",{"t":"首页"},["/zh_backup/index.html","/zh_backup/README.md"]],
  ["v-5890a66c","/components/conversion/hive-convert.html",{"t":"bitsail-convertion-flink-hive"},["/components/conversion/hive-convert","/components/conversion/hive-convert.md"]],
  ["v-bafe00f4","/components/conversion/introduction.html",{"t":"bitsail-conversion-flink"},["/components/conversion/introduction","/components/conversion/introduction.md"]],
  ["v-1636a178","/components/clients/introduction.html",{"t":"bitsail-component-clients"},["/components/clients/introduction","/components/clients/introduction.md"]],
  ["v-a1abc786","/components/format/hive-format.html",{"t":"bitsail-component-format-flink-hive"},["/components/format/hive-format","/components/format/hive-format.md"]],
  ["v-05f687b2","/components/format/introduction.html",{"t":"bitsail-component-formats-flink"},["/components/format/introduction","/components/format/introduction.md"]],
  ["v-2a6ab5b5","/components/format/json-format.html",{"t":"bitsail-component-format-flink-json"},["/components/format/json-format","/components/format/json-format.md"]],
  ["v-1526464f","/components/parser/introduction.html",{"t":"bitsail-flink-row-parser"},["/components/parser/introduction","/components/parser/introduction.md"]],
  ["v-6f6e3de2","/connectors/Jdbc/jdbc_example.html",{"t":"Jdbc连接器示例"},["/connectors/Jdbc/jdbc_example","/connectors/Jdbc/jdbc_example.md"]],
  ["v-7019f9ea","/connectors/Jdbc/jdbc_zh.html",{"t":"Jdbc Connector 介绍"},["/connectors/Jdbc/jdbc_zh","/connectors/Jdbc/jdbc_zh.md"]],
  ["v-04c5c3c8","/connectors/StreamingFile/StreamingFile.html",{"t":"StreamingFile"},["/connectors/StreamingFile/StreamingFile","/connectors/StreamingFile/StreamingFile.md"]],
  ["v-63f9ac1e","/connectors/StreamingFile/StreamingFile_Example.html",{"t":"HDFS's Example"},["/connectors/StreamingFile/StreamingFile_Example","/connectors/StreamingFile/StreamingFile_Example.md"]],
  ["v-6deacc0e","/connectors/doris/doris-example.html",{"t":"Doris连接器配置示例"},["/connectors/doris/doris-example","/connectors/doris/doris-example.md"]],
  ["v-cea9bd14","/connectors/doris/doris.html",{"t":"Doris连接器"},["/connectors/doris/doris","/connectors/doris/doris.md"]],
  ["v-03696957","/connectors/druid/druid-example.html",{"t":"Druid连接器配置示例"},["/connectors/druid/druid-example","/connectors/druid/druid-example.md"]],
  ["v-9973a258","/connectors/druid/druid.html",{"t":"Druid连接器"},["/connectors/druid/druid","/connectors/druid/druid.md"]],
  ["v-4e4b37e1","/connectors/elasticsearch/elasticsearch-example.html",{"t":"Elasticsearch连接器使用示例"},["/connectors/elasticsearch/elasticsearch-example","/connectors/elasticsearch/elasticsearch-example.md"]],
  ["v-0abc275e","/connectors/elasticsearch/elasticsearch.html",{"t":"Elasticsearch连接器"},["/connectors/elasticsearch/elasticsearch","/connectors/elasticsearch/elasticsearch.md"]],
  ["v-2f08afd7","/connectors/ftp/ftp-example.html",{"t":"FTP/SFTP连接器使用示例"},["/connectors/ftp/ftp-example","/connectors/ftp/ftp-example.md"]],
  ["v-a8581558","/connectors/ftp/ftp.html",{"t":"FTP/SFTP连接器"},["/connectors/ftp/ftp","/connectors/ftp/ftp.md"]],
  ["v-56ae5006","/connectors/hadoop/hadoop-example.html",{"t":"Hadoop连接器使用示例"},["/connectors/hadoop/hadoop-example","/connectors/hadoop/hadoop-example.md"]],
  ["v-be4cb90c","/connectors/hadoop/hadoop.html",{"t":"Hadoop连接器"},["/connectors/hadoop/hadoop","/connectors/hadoop/hadoop.md"]],
  ["v-00332ce9","/connectors/hbase/hbase-example.html",{"t":"Hbase 连接器示例"},["/connectors/hbase/hbase-example","/connectors/hbase/hbase-example.md"]],
  ["v-5d64b734","/connectors/hbase/hbase.html",{"t":"HBase连接器"},["/connectors/hbase/hbase","/connectors/hbase/hbase.md"]],
  ["v-78b9429d","/connectors/hive/hive-example.html",{"t":"Hive连接器使用示例"},["/connectors/hive/hive-example","/connectors/hive/hive-example.md"]],
  ["v-9a62a3cc","/connectors/hive/hive.html",{"t":"hive连接器"},["/connectors/hive/hive","/connectors/hive/hive.md"]],
  ["v-73e56546","/connectors/hudi/hudi-example.html",{"t":"Hudi连接器使用示例"},["/connectors/hudi/hudi-example","/connectors/hudi/hudi-example.md"]],
  ["v-518d0e4c","/connectors/hudi/hudi.html",{"t":"Hudi连接器"},["/connectors/hudi/hudi","/connectors/hudi/hudi.md"]],
  ["v-55e6850f","/connectors/kafka/kafka-example.html",{"t":"Kafka连接器使用示例"},["/connectors/kafka/kafka-example","/connectors/kafka/kafka-example.md"]],
  ["v-d6d2fae8","/connectors/kafka/kafka.html",{"t":"Kafka连接器"},["/connectors/kafka/kafka","/connectors/kafka/kafka.md"]],
  ["v-f403c086","/connectors/kudu/kudu-example.html",{"t":"Kudu连接器配置示例"},["/connectors/kudu/kudu-example","/connectors/kudu/kudu-example.md"]],
  ["v-48d2ab3a","/connectors/kudu/kudu.html",{"t":"Kudu连接器"},["/connectors/kudu/kudu","/connectors/kudu/kudu.md"]],
  ["v-4f66760e","/connectors/larksheet/larksheet-example.html",{"t":"LarkSheet connector examples"},["/connectors/larksheet/larksheet-example","/connectors/larksheet/larksheet-example.md"]],
  ["v-16484c76","/connectors/larksheet/larksheet.html",{"t":"飞书表格连接器"},["/connectors/larksheet/larksheet","/connectors/larksheet/larksheet.md"]],
  ["v-23932192","/connectors/mongodb/mongodb-example.html",{"t":"MongoDB连接器配置示例"},["/connectors/mongodb/mongodb-example","/connectors/mongodb/mongodb-example.md"]],
  ["v-4ae714b4","/connectors/mongodb/mongodb.html",{"t":"MongoDB连接器"},["/connectors/mongodb/mongodb","/connectors/mongodb/mongodb.md"]],
  ["v-d9846f36","/connectors/redis/redis-example.html",{"t":"Redis连接器配置示例"},["/connectors/redis/redis-example","/connectors/redis/redis-example.md"]],
  ["v-e352256a","/connectors/redis/redis-v1-example.html",{"t":"Redis连接器配置示例"},["/connectors/redis/redis-v1-example","/connectors/redis/redis-v1-example.md"]],
  ["v-08be3270","/connectors/redis/redis-v1.html",{"t":"Redis连接器"},["/connectors/redis/redis-v1","/connectors/redis/redis-v1.md"]],
  ["v-160d083c","/connectors/redis/redis.html",{"t":"Redis连接器"},["/connectors/redis/redis","/connectors/redis/redis.md"]],
  ["v-7f48511d","/connectors/rocketmq/rocketmq-example.html",{"t":"RocketMQ连接器配置示例"},["/connectors/rocketmq/rocketmq-example","/connectors/rocketmq/rocketmq-example.md"]],
  ["v-36943c9a","/connectors/rocketmq/rocketmq.html",{"t":"RocketMQ连接器"},["/connectors/rocketmq/rocketmq","/connectors/rocketmq/rocketmq.md"]],
  ["v-0292b212","/zh/contribute/contribute.html",{"t":"贡献者指引"},["/zh/contribute/contribute","/zh/contribute/contribute.md"]],
  ["v-652fd879","/zh/documents/introduce.html",{"t":""},["/zh/documents/introduce","/zh/documents/introduce.md"]],
  ["v-60d3793c","/zh/release/release.html",{"t":""},["/zh/release/release","/zh/release/release.md"]],
  ["v-227996fc","/zh/start/config.html",{"t":"Job Configuration Description"},["/zh/start/config","/zh/start/config.md"]],
  ["v-ded9b63a","/zh/start/config_zh.html",{"t":"任务配置说明"},["/zh/start/config_zh","/zh/start/config_zh.md"]],
  ["v-2089109a","/zh/start/contributing.html",{"t":"Contributor Guide"},["/zh/start/contributing","/zh/start/contributing.md"]],
  ["v-06a0695f","/zh/start/deployment.html",{"t":"Deployment Guide"},["/zh/start/deployment","/zh/start/deployment.md"]],
  ["v-b0c43234","/zh/start/deployment_zh.html",{"t":"部署指南"},["/zh/start/deployment_zh","/zh/start/deployment_zh.md"]],
  ["v-7e0dd183","/zh/start/env_setup.html",{"t":"Environment Setup"},["/zh/start/env_setup","/zh/start/env_setup.md"]],
  ["v-e730477c","/zh/start/env_setup_zh.html",{"t":"环境配置"},["/zh/start/env_setup_zh","/zh/start/env_setup_zh.md"]],
  ["v-8933d2dc","/zh/team/team.html",{"t":""},["/zh/team/team","/zh/team/team.md"]],
  ["v-3bd9aaec","/zh/usercases/case.html",{"t":""},["/zh/usercases/case","/zh/usercases/case.md"]],
  ["v-689daf1b","/zh_backup/components/introduction.html",{"t":"bitsail-components"},["/zh_backup/components/introduction","/zh_backup/components/introduction.md"]],
  ["v-791075cb","/zh_backup/connectors/introduction.html",{"t":"BitSail 连接器"},["/zh_backup/connectors/introduction","/zh_backup/connectors/introduction.md"]],
  ["v-2ba82ef5","/zh_backup/start/config.html",{"t":"任务配置说明"},["/zh_backup/start/config","/zh_backup/start/config.md"]],
  ["v-8891ae66","/zh_backup/start/contributing.html",{"t":"贡献者指引"},["/zh_backup/start/contributing","/zh_backup/start/contributing.md"]],
  ["v-0a661b5c","/zh_backup/start/deployment.html",{"t":"部署指南"},["/zh_backup/start/deployment","/zh_backup/start/deployment.md"]],
  ["v-4efa43a0","/zh_backup/start/env_setup.html",{"t":"环境配置"},["/zh_backup/start/env_setup","/zh_backup/start/env_setup.md"]],
  ["v-85c6ed36","/zh/documents/components/introduction.html",{"t":"bitsail-components"},["/zh/documents/components/introduction","/zh/documents/components/introduction.md"]],
  ["v-c39efdc0","/zh/documents/components/introduction_zh.html",{"t":"bitsail-components"},["/zh/documents/components/introduction_zh","/zh/documents/components/introduction_zh.md"]],
  ["v-7f4b7af6","/zh/documents/designs/How%20to%20calculate%20parallelism%20automatically.html",{"t":""},["/zh/documents/designs/How to calculate parallelism automatically.html","/zh/documents/designs/How%20to%20calculate%20parallelism%20automatically","/zh/documents/designs/How to calculate parallelism automatically.md","/zh/documents/designs/How%20to%20calculate%20parallelism%20automatically.md"]],
  ["v-64e15fd6","/zh/documents/connectors/introduction.html",{"t":"BitSail connectors"},["/zh/documents/connectors/introduction","/zh/documents/connectors/introduction.md"]],
  ["v-8a600720","/zh/documents/connectors/introduction_zh.html",{"t":"BitSail 连接器"},["/zh/documents/connectors/introduction_zh","/zh/documents/connectors/introduction_zh.md"]],
  ["v-54c56ad4","/zh_backup/components/clients/introduction.html",{"t":"bitsail-component-clients"},["/zh_backup/components/clients/introduction","/zh_backup/components/clients/introduction.md"]],
  ["v-841bd424","/zh_backup/components/conversion/hive-convert.html",{"t":"bitsail-convertion-flink-hive"},["/zh_backup/components/conversion/hive-convert","/zh_backup/components/conversion/hive-convert.md"]],
  ["v-e6892eac","/zh_backup/components/conversion/introduction.html",{"t":"bitsail-conversion-flink"},["/zh_backup/components/conversion/introduction","/zh_backup/components/conversion/introduction.md"]],
  ["v-12538c99","/zh_backup/components/format/hive-format.html",{"t":"bitsail-component-format-flink-hive"},["/zh_backup/components/format/hive-format","/zh_backup/components/format/hive-format.md"]],
  ["v-01ed516a","/zh_backup/components/format/introduction.html",{"t":"bitsail-component-formats-flink"},["/zh_backup/components/format/introduction","/zh_backup/components/format/introduction.md"]],
  ["v-e4d7b3de","/zh_backup/components/format/json-format.html",{"t":"bitsail-component-format-flink-json"},["/zh_backup/components/format/json-format","/zh_backup/components/format/json-format.md"]],
  ["v-172ae173","/zh_backup/components/parser/introduction.html",{"t":"bitsail-flink-row-parser"},["/zh_backup/components/parser/introduction","/zh_backup/components/parser/introduction.md"]],
  ["v-377c159a","/zh_backup/connectors/Jdbc/jdbc_example.html",{"t":"Jdbc连接器示例"},["/zh_backup/connectors/Jdbc/jdbc_example","/zh_backup/connectors/Jdbc/jdbc_example.md"]],
  ["v-619ee867","/zh_backup/connectors/Jdbc/jdbc_zh.html",{"t":"Jdbc Connector 介绍"},["/zh_backup/connectors/Jdbc/jdbc_zh","/zh_backup/connectors/Jdbc/jdbc_zh.md"]],
  ["v-69e195c6","/zh_backup/connectors/doris/doris-example.html",{"t":"Doris连接器配置示例"},["/zh_backup/connectors/doris/doris-example","/zh_backup/connectors/doris/doris-example.md"]],
  ["v-197f209a","/zh_backup/connectors/doris/doris.html",{"t":"Doris连接器"},["/zh_backup/connectors/doris/doris","/zh_backup/connectors/doris/doris.md"]],
  ["v-04765540","/zh_backup/connectors/StreamingFile/StreamingFile.html",{"t":"StreamingFile"},["/zh_backup/connectors/StreamingFile/StreamingFile","/zh_backup/connectors/StreamingFile/StreamingFile.md"]],
  ["v-7954fd15","/zh_backup/connectors/StreamingFile/StreamingFile_Example.html",{"t":"HDFS's Example"},["/zh_backup/connectors/StreamingFile/StreamingFile_Example","/zh_backup/connectors/StreamingFile/StreamingFile_Example.md"]],
  ["v-056e047b","/zh_backup/connectors/druid/druid-example.html",{"t":"Druid连接器配置示例"},["/zh_backup/connectors/druid/druid-example","/zh_backup/connectors/druid/druid-example.md"]],
  ["v-341a2df8","/zh_backup/connectors/druid/druid.html",{"t":"Druid连接器"},["/zh_backup/connectors/druid/druid","/zh_backup/connectors/druid/druid.md"]],
  ["v-0cc5e9f6","/zh_backup/connectors/elasticsearch/elasticsearch-example.html",{"t":"Elasticsearch连接器使用示例"},["/zh_backup/connectors/elasticsearch/elasticsearch-example","/zh_backup/connectors/elasticsearch/elasticsearch-example.md"]],
  ["v-11955e82","/zh_backup/connectors/elasticsearch/elasticsearch.html",{"t":"Elasticsearch连接器"},["/zh_backup/connectors/elasticsearch/elasticsearch","/zh_backup/connectors/elasticsearch/elasticsearch.md"]],
  ["v-19c07cfb","/zh_backup/connectors/ftp/ftp-example.html",{"t":"FTP/SFTP连接器使用示例"},["/zh_backup/connectors/ftp/ftp-example","/zh_backup/connectors/ftp/ftp-example.md"]],
  ["v-e6a5b310","/zh_backup/connectors/ftp/ftp.html",{"t":"FTP/SFTP连接器"},["/zh_backup/connectors/ftp/ftp","/zh_backup/connectors/ftp/ftp.md"]],
  ["v-67f33a21","/zh_backup/connectors/hadoop/hadoop-example.html",{"t":"Hadoop连接器使用示例"},["/zh_backup/connectors/hadoop/hadoop-example","/zh_backup/connectors/hadoop/hadoop-example.md"]],
  ["v-3caa699e","/zh_backup/connectors/hadoop/hadoop.html",{"t":"Hadoop连接器"},["/zh_backup/connectors/hadoop/hadoop","/zh_backup/connectors/hadoop/hadoop.md"]],
  ["v-0237c80d","/zh_backup/connectors/hbase/hbase-example.html",{"t":"Hbase 连接器示例"},["/zh_backup/connectors/hbase/hbase-example","/zh_backup/connectors/hbase/hbase-example.md"]],
  ["v-5221a38a","/zh_backup/connectors/hbase/hbase.html",{"t":"HBase连接器"},["/zh_backup/connectors/hbase/hbase","/zh_backup/connectors/hbase/hbase.md"]],
  ["v-d69b527e","/zh_backup/connectors/hive/hive-example.html",{"t":"Hive连接器使用示例"},["/zh_backup/connectors/hive/hive-example","/zh_backup/connectors/hive/hive-example.md"]],
  ["v-7bbfb384","/zh_backup/connectors/hive/hive.html",{"t":"hive连接器"},["/zh_backup/connectors/hive/hive","/zh_backup/connectors/hive/hive.md"]],
  ["v-3bf33cfe","/zh_backup/connectors/hudi/hudi-example.html",{"t":"Hudi连接器使用示例"},["/zh_backup/connectors/hudi/hudi-example","/zh_backup/connectors/hudi/hudi-example.md"]],
  ["v-32ea1e04","/zh_backup/connectors/hudi/hudi.html",{"t":"Hudi连接器"},["/zh_backup/connectors/hudi/hudi","/zh_backup/connectors/hudi/hudi.md"]],
  ["v-bc11983e","/zh_backup/connectors/kudu/kudu-example.html",{"t":"Kudu连接器配置示例"},["/zh_backup/connectors/kudu/kudu-example","/zh_backup/connectors/kudu/kudu-example.md"]],
  ["v-5824235e","/zh_backup/connectors/kudu/kudu.html",{"t":"Kudu连接器"},["/zh_backup/connectors/kudu/kudu","/zh_backup/connectors/kudu/kudu.md"]],
  ["v-57eb2033","/zh_backup/connectors/kafka/kafka-example.html",{"t":"Kafka连接器使用示例"},["/zh_backup/connectors/kafka/kafka-example","/zh_backup/connectors/kafka/kafka-example.md"]],
  ["v-156a81b0","/zh_backup/connectors/kafka/kafka.html",{"t":"Kafka连接器"},["/zh_backup/connectors/kafka/kafka","/zh_backup/connectors/kafka/kafka.md"]],
  ["v-41b407c6","/zh_backup/connectors/larksheet/larksheet-example.html",{"t":"LarkSheet connector examples"},["/zh_backup/connectors/larksheet/larksheet-example","/zh_backup/connectors/larksheet/larksheet-example.md"]],
  ["v-184ce79a","/zh_backup/connectors/larksheet/larksheet.html",{"t":"飞书表格连接器"},["/zh_backup/connectors/larksheet/larksheet","/zh_backup/connectors/larksheet/larksheet.md"]],
  ["v-4f1e4f4a","/zh_backup/connectors/mongodb/mongodb-example.html",{"t":"MongoDB连接器配置示例"},["/zh_backup/connectors/mongodb/mongodb-example","/zh_backup/connectors/mongodb/mongodb-example.md"]],
  ["v-359ee1d8","/zh_backup/connectors/mongodb/mongodb.html",{"t":"MongoDB连接器"},["/zh_backup/connectors/mongodb/mongodb","/zh_backup/connectors/mongodb/mongodb.md"]],
  ["v-d57b38ee","/zh_backup/connectors/redis/redis-example.html",{"t":"Redis连接器配置示例"},["/zh_backup/connectors/redis/redis-example","/zh_backup/connectors/redis/redis-example.md"]],
  ["v-6458cfa7","/zh_backup/connectors/redis/redis-v1-example.html",{"t":"Redis连接器配置示例"},["/zh_backup/connectors/redis/redis-v1-example","/zh_backup/connectors/redis/redis-v1-example.md"]],
  ["v-4c2e35b8","/zh_backup/connectors/redis/redis-v1.html",{"t":"Redis连接器"},["/zh_backup/connectors/redis/redis-v1","/zh_backup/connectors/redis/redis-v1.md"]],
  ["v-75cd7b06","/zh_backup/connectors/redis/redis.html",{"t":"Redis连接器"},["/zh_backup/connectors/redis/redis","/zh_backup/connectors/redis/redis.md"]],
  ["v-76e5fd7e","/zh_backup/connectors/rocketmq/rocketmq-example.html",{"t":"RocketMQ连接器配置示例"},["/zh_backup/connectors/rocketmq/rocketmq-example","/zh_backup/connectors/rocketmq/rocketmq-example.md"]],
  ["v-528d50be","/zh_backup/connectors/rocketmq/rocketmq.html",{"t":"RocketMQ连接器"},["/zh_backup/connectors/rocketmq/rocketmq","/zh_backup/connectors/rocketmq/rocketmq.md"]],
  ["v-6d925b1e","/zh/documents/components/clients/introduction.html",{"t":"bitsail-component-clients"},["/zh/documents/components/clients/introduction","/zh/documents/components/clients/introduction.md"]],
  ["v-7cf128c7","/zh/documents/components/clients/introduction_zh.html",{"t":"bitsail-component-clients"},["/zh/documents/components/clients/introduction_zh","/zh/documents/components/clients/introduction_zh.md"]],
  ["v-623e6d38","/zh/documents/components/conversion/hive-convert.html",{"t":"bitsail-convertion-flink-hive"},["/zh/documents/components/conversion/hive-convert","/zh/documents/components/conversion/hive-convert.md"]],
  ["v-2303ccc1","/zh/documents/components/conversion/hive-convert_zh.html",{"t":"bitsail-convertion-flink-hive"},["/zh/documents/components/conversion/hive-convert_zh","/zh/documents/components/conversion/hive-convert_zh.md"]],
  ["v-c4abc7c0","/zh/documents/components/conversion/introduction.html",{"t":"bitsail-conversion-flink"},["/zh/documents/components/conversion/introduction","/zh/documents/components/conversion/introduction.md"]],
  ["v-1936b085","/zh/documents/components/conversion/introduction_zh.html",{"t":"bitsail-conversion-flink"},["/zh/documents/components/conversion/introduction_zh","/zh/documents/components/conversion/introduction_zh.md"]],
  ["v-2d57f13a","/zh/documents/components/format/hive-format.html",{"t":"bitsail-component-format-flink-hive"},["/zh/documents/components/format/hive-format","/zh/documents/components/format/hive-format.md"]],
  ["v-2bdf5a62","/zh/documents/components/format/hive-format_zh.html",{"t":"bitsail-component-format-flink-hive"},["/zh/documents/components/format/hive-format_zh","/zh/documents/components/format/hive-format_zh.md"]],
  ["v-081835c1","/zh/documents/components/format/introduction.html",{"t":"bitsail-component-formats-flink"},["/zh/documents/components/format/introduction","/zh/documents/components/format/introduction.md"]],
  ["v-7baf2744","/zh/documents/components/format/introduction_zh.html",{"t":"bitsail-component-formats-flink"},["/zh/documents/components/format/introduction_zh","/zh/documents/components/format/introduction_zh.md"]],
  ["v-6494a0db","/zh/documents/components/format/json-format.html",{"t":"bitsail-component-format-flink-json"},["/zh/documents/components/format/json-format","/zh/documents/components/format/json-format.md"]],
  ["v-2e62adea","/zh/documents/components/format/json-format_zh.html",{"t":"bitsail-component-format-flink-json"},["/zh/documents/components/format/json-format_zh","/zh/documents/components/format/json-format_zh.md"]],
  ["v-2039bfe9","/zh/documents/components/parser/introduction.html",{"t":"BitSail-flink-row-parser"},["/zh/documents/components/parser/introduction","/zh/documents/components/parser/introduction.md"]],
  ["v-ba88e7c8","/zh/documents/components/parser/introduction_zh.html",{"t":"bitsail-flink-row-parser"},["/zh/documents/components/parser/introduction_zh","/zh/documents/components/parser/introduction_zh.md"]],
  ["v-3767cd18","/zh/documents/connectors/Jdbc/jdbc.html",{"t":"Jdbc Connector"},["/zh/documents/connectors/Jdbc/jdbc","/zh/documents/connectors/Jdbc/jdbc.md"]],
  ["v-2d41f929","/zh/documents/connectors/Jdbc/jdbc_example.html",{"t":"Jdbc Example"},["/zh/documents/connectors/Jdbc/jdbc_example","/zh/documents/connectors/Jdbc/jdbc_example.md"]],
  ["v-32b9cadc","/zh/documents/connectors/Jdbc/jdbc_example_zh.html",{"t":"Jdbc连接器示例"},["/zh/documents/connectors/Jdbc/jdbc_example_zh","/zh/documents/connectors/Jdbc/jdbc_example_zh.md"]],
  ["v-93c47a9e","/zh/documents/connectors/Jdbc/jdbc_zh.html",{"t":"Jdbc Connector 介绍"},["/zh/documents/connectors/Jdbc/jdbc_zh","/zh/documents/connectors/Jdbc/jdbc_zh.md"]],
  ["v-615b4494","/zh/documents/connectors/StreamingFile/StreamingFile.html",{"t":"StreamingFile"},["/zh/documents/connectors/StreamingFile/StreamingFile","/zh/documents/connectors/StreamingFile/StreamingFile.md"]],
  ["v-23342f8b","/zh/documents/connectors/StreamingFile/StreamingFile_Example.html",{"t":""},["/zh/documents/connectors/StreamingFile/StreamingFile_Example","/zh/documents/connectors/StreamingFile/StreamingFile_Example.md"]],
  ["v-774201a2","/zh/documents/connectors/StreamingFile/StreamingFile_zh.html",{"t":"StreamingFile"},["/zh/documents/connectors/StreamingFile/StreamingFile_zh","/zh/documents/connectors/StreamingFile/StreamingFile_zh.md"]],
  ["v-57c3d8da","/zh/documents/connectors/doris/doris-example.html",{"t":"Doris connector examples"},["/zh/documents/connectors/doris/doris-example","/zh/documents/connectors/doris/doris-example.md"]],
  ["v-4b40bf9c","/zh/documents/connectors/doris/doris-example_zh.html",{"t":"Doris连接器配置示例"},["/zh/documents/connectors/doris/doris-example_zh","/zh/documents/connectors/doris/doris-example_zh.md"]],
  ["v-13f6d510","/zh/documents/connectors/doris/doris.html",{"t":"Doris connector"},["/zh/documents/connectors/doris/doris","/zh/documents/connectors/doris/doris.md"]],
  ["v-7907dcd6","/zh/documents/connectors/doris/doris_zh.html",{"t":"Doris连接器"},["/zh/documents/connectors/doris/doris_zh","/zh/documents/connectors/doris/doris_zh.md"]],
  ["v-0e7ce2f1","/zh/documents/connectors/druid/druid-example.html",{"t":"Druid connector configuration examples"},["/zh/documents/connectors/druid/druid-example","/zh/documents/connectors/druid/druid-example.md"]],
  ["v-79852c14","/zh/documents/connectors/druid/druid-example_zh.html",{"t":"Druid连接器配置示例"},["/zh/documents/connectors/druid/druid-example_zh","/zh/documents/connectors/druid/druid-example_zh.md"]],
  ["v-2e91e26e","/zh/documents/connectors/druid/druid.html",{"t":"Druid connector"},["/zh/documents/connectors/druid/druid","/zh/documents/connectors/druid/druid.md"]],
  ["v-35d6c112","/zh/documents/connectors/druid/druid_zh.html",{"t":"Druid连接器"},["/zh/documents/connectors/druid/druid_zh","/zh/documents/connectors/druid/druid_zh.md"]],
  ["v-b907850a","/zh/documents/connectors/elasticsearch/elasticsearch-example.html",{"t":"Elasticsearch connector examples"},["/zh/documents/connectors/elasticsearch/elasticsearch-example","/zh/documents/connectors/elasticsearch/elasticsearch-example.md"]],
  ["v-794e4d4a","/zh/documents/connectors/elasticsearch/elasticsearch-example_zh.html",{"t":"Elasticsearch连接器使用示例"},["/zh/documents/connectors/elasticsearch/elasticsearch-example_zh","/zh/documents/connectors/elasticsearch/elasticsearch-example_zh.md"]],
  ["v-471d3210","/zh/documents/connectors/elasticsearch/elasticsearch.html",{"t":"Elasticsearch connector"},["/zh/documents/connectors/elasticsearch/elasticsearch","/zh/documents/connectors/elasticsearch/elasticsearch.md"]],
  ["v-99d552a6","/zh/documents/connectors/elasticsearch/elasticsearch_zh.html",{"t":"Elasticsearch连接器"},["/zh/documents/connectors/elasticsearch/elasticsearch_zh","/zh/documents/connectors/elasticsearch/elasticsearch_zh.md"]],
  ["v-2085f31e","/zh/documents/connectors/ftp/ftp-example.html",{"t":"FTP/SFTP connector examples"},["/zh/documents/connectors/ftp/ftp-example","/zh/documents/connectors/ftp/ftp-example.md"]],
  ["v-20685894","/zh/documents/connectors/ftp/ftp-example_zh.html",{"t":"FTP/SFTP连接器使用示例"},["/zh/documents/connectors/ftp/ftp-example_zh","/zh/documents/connectors/ftp/ftp-example_zh.md"]],
  ["v-3424f424","/zh/documents/connectors/ftp/ftp.html",{"t":"FTP/SFTP connector"},["/zh/documents/connectors/ftp/ftp","/zh/documents/connectors/ftp/ftp.md"]],
  ["v-762c4bf7","/zh/documents/connectors/ftp/ftp_zh.html",{"t":"FTP/SFTP连接器"},["/zh/documents/connectors/ftp/ftp_zh","/zh/documents/connectors/ftp/ftp_zh.md"]],
  ["v-68c45317","/zh/documents/connectors/hadoop/hadoop-example.html",{"t":"Hadoop connector examples"},["/zh/documents/connectors/hadoop/hadoop-example","/zh/documents/connectors/hadoop/hadoop-example.md"]],
  ["v-58d9022e","/zh/documents/connectors/hadoop/hadoop-example_zh.html",{"t":"Hadoop连接器使用示例"},["/zh/documents/connectors/hadoop/hadoop-example_zh","/zh/documents/connectors/hadoop/hadoop-example_zh.md"]],
  ["v-7806d894","/zh/documents/connectors/hadoop/hadoop.html",{"t":"Hadoop connector"},["/zh/documents/connectors/hadoop/hadoop","/zh/documents/connectors/hadoop/hadoop.md"]],
  ["v-27052f91","/zh/documents/connectors/hadoop/hadoop_zh.html",{"t":"Hadoop连接器"},["/zh/documents/connectors/hadoop/hadoop_zh","/zh/documents/connectors/hadoop/hadoop_zh.md"]],
  ["v-0b46a683","/zh/documents/connectors/hbase/hbase-example.html",{"t":"Hbase connector examples"},["/zh/documents/connectors/hbase/hbase-example","/zh/documents/connectors/hbase/hbase-example.md"]],
  ["v-95fa317c","/zh/documents/connectors/hbase/hbase-example_zh.html",{"t":"Hbase 连接器示例"},["/zh/documents/connectors/hbase/hbase-example_zh","/zh/documents/connectors/hbase/hbase-example_zh.md"]],
  ["v-4c995800","/zh/documents/connectors/hbase/hbase.html",{"t":"HBase connector"},["/zh/documents/connectors/hbase/hbase","/zh/documents/connectors/hbase/hbase.md"]],
  ["v-6b1f68a5","/zh/documents/connectors/hbase/hbase_zh.html",{"t":"HBase连接器"},["/zh/documents/connectors/hbase/hbase_zh","/zh/documents/connectors/hbase/hbase_zh.md"]],
  ["v-449b4a92","/zh/documents/connectors/hive/hive-example.html",{"t":"Hive connector examples"},["/zh/documents/connectors/hive/hive-example","/zh/documents/connectors/hive/hive-example.md"]],
  ["v-cebb52e4","/zh/documents/connectors/hive/hive-example_zh.html",{"t":"Hive连接器使用示例"},["/zh/documents/connectors/hive/hive-example_zh","/zh/documents/connectors/hive/hive-example_zh.md"]],
  ["v-6672ff98","/zh/documents/connectors/hive/hive.html",{"t":"Hive connector"},["/zh/documents/connectors/hive/hive","/zh/documents/connectors/hive/hive.md"]],
  ["v-7218e3f1","/zh/documents/connectors/hive/hive_zh.html",{"t":"hive连接器"},["/zh/documents/connectors/hive/hive_zh","/zh/documents/connectors/hive/hive_zh.md"]],
  ["v-2b066577","/zh/documents/connectors/hudi/hudi-example.html",{"t":"Hudi connector examples"},["/zh/documents/connectors/hudi/hudi-example","/zh/documents/connectors/hudi/hudi-example.md"]],
  ["v-5fb153ce","/zh/documents/connectors/hudi/hudi-example_zh.html",{"t":"Hudi连接器使用示例"},["/zh/documents/connectors/hudi/hudi-example_zh","/zh/documents/connectors/hudi/hudi-example_zh.md"]],
  ["v-1d9d6a18","/zh/documents/connectors/hudi/hudi.html",{"t":"Hudi connector"},["/zh/documents/connectors/hudi/hudi","/zh/documents/connectors/hudi/hudi.md"]],
  ["v-59992131","/zh/documents/connectors/hudi/hudi_zh.html",{"t":"Hudi连接器"},["/zh/documents/connectors/hudi/hudi_zh","/zh/documents/connectors/hudi/hudi_zh.md"]],
  ["v-60f9fea9","/zh/documents/connectors/kafka/kafka-example.html",{"t":"Kafka connector examples"},["/zh/documents/connectors/kafka/kafka-example","/zh/documents/connectors/kafka/kafka-example.md"]],
  ["v-72fc5548","/zh/documents/connectors/kafka/kafka-example_zh.html",{"t":"Kafka连接器使用示例"},["/zh/documents/connectors/kafka/kafka-example_zh","/zh/documents/connectors/kafka/kafka-example_zh.md"]],
  ["v-0fe23626","/zh/documents/connectors/kafka/kafka.html",{"t":"Kafka connector"},["/zh/documents/connectors/kafka/kafka","/zh/documents/connectors/kafka/kafka.md"]],
  ["v-3059de82","/zh/documents/connectors/kafka/kafka_zh.html",{"t":"Kafka连接器"},["/zh/documents/connectors/kafka/kafka_zh","/zh/documents/connectors/kafka/kafka_zh.md"]],
  ["v-2a119052","/zh/documents/connectors/kudu/kudu-example.html",{"t":"Kudu connector configration examples"},["/zh/documents/connectors/kudu/kudu-example","/zh/documents/connectors/kudu/kudu-example.md"]],
  ["v-8d3a3524","/zh/documents/connectors/kudu/kudu-example_zh.html",{"t":"Kudu连接器配置示例"},["/zh/documents/connectors/kudu/kudu-example_zh","/zh/documents/connectors/kudu/kudu-example_zh.md"]],
  ["v-62ca7d54","/zh/documents/connectors/kudu/kudu.html",{"t":"Kudu connector"},["/zh/documents/connectors/kudu/kudu","/zh/documents/connectors/kudu/kudu.md"]],
  ["v-27735a5e","/zh/documents/connectors/kudu/kudu_zh.html",{"t":"Kudu连接器"},["/zh/documents/connectors/kudu/kudu_zh","/zh/documents/connectors/kudu/kudu_zh.md"]],
  ["v-abfbf6da","/zh/documents/connectors/larksheet/larksheet-example.html",{"t":"LarkSheet connector examples"},["/zh/documents/connectors/larksheet/larksheet-example","/zh/documents/connectors/larksheet/larksheet-example.md"]],
  ["v-f9abe19c","/zh/documents/connectors/larksheet/larksheet-example_zh.html",{"t":"LarkSheet connector examples"},["/zh/documents/connectors/larksheet/larksheet-example_zh","/zh/documents/connectors/larksheet/larksheet-example_zh.md"]],
  ["v-215bc610","/zh/documents/connectors/larksheet/larksheet.html",{"t":"LarkSheet connector"},["/zh/documents/connectors/larksheet/larksheet","/zh/documents/connectors/larksheet/larksheet.md"]],
  ["v-79258095","/zh/documents/connectors/larksheet/larksheet_zh.html",{"t":"飞书表格连接器"},["/zh/documents/connectors/larksheet/larksheet_zh","/zh/documents/connectors/larksheet/larksheet_zh.md"]],
  ["v-2d40e85e","/zh/documents/connectors/mongodb/mongodb-example.html",{"t":"MongoDB connector examples"},["/zh/documents/connectors/mongodb/mongodb-example","/zh/documents/connectors/mongodb/mongodb-example.md"]],
  ["v-68275734","/zh/documents/connectors/mongodb/mongodb-example_zh.html",{"t":"MongoDB连接器配置示例"},["/zh/documents/connectors/mongodb/mongodb-example_zh","/zh/documents/connectors/mongodb/mongodb-example_zh.md"]],
  ["v-0b9b6b4e","/zh/documents/connectors/mongodb/mongodb.html",{"t":"MongoDB connector"},["/zh/documents/connectors/mongodb/mongodb","/zh/documents/connectors/mongodb/mongodb.md"]],
  ["v-3da3ea97","/zh/documents/connectors/mongodb/mongodb_zh.html",{"t":"MongoDB连接器"},["/zh/documents/connectors/mongodb/mongodb_zh","/zh/documents/connectors/mongodb/mongodb_zh.md"]],
  ["v-c35d7c02","/zh/documents/connectors/redis/redis-example.html",{"t":"Redis connector examples"},["/zh/documents/connectors/redis/redis-example","/zh/documents/connectors/redis/redis-example.md"]],
  ["v-1466ca46","/zh/documents/connectors/redis/redis-example_zh.html",{"t":"Redis连接器配置示例"},["/zh/documents/connectors/redis/redis-example_zh","/zh/documents/connectors/redis/redis-example_zh.md"]],
  ["v-7daad571","/zh/documents/connectors/redis/redis-v1-example.html",{"t":"Redis connector examples"},["/zh/documents/connectors/redis/redis-v1-example","/zh/documents/connectors/redis/redis-v1-example.md"]],
  ["v-e517acd8","/zh/documents/connectors/redis/redis-v1-example_zh.html",{"t":"Redis连接器配置示例"},["/zh/documents/connectors/redis/redis-v1-example_zh","/zh/documents/connectors/redis/redis-v1-example_zh.md"]],
  ["v-0a1a54ee","/zh/documents/connectors/redis/redis-v1.html",{"t":"Redis connector"},["/zh/documents/connectors/redis/redis-v1","/zh/documents/connectors/redis/redis-v1.md"]],
  ["v-30991cf7","/zh/documents/connectors/redis/redis-v1_zh.html",{"t":"Redis连接器"},["/zh/documents/connectors/redis/redis-v1_zh","/zh/documents/connectors/redis/redis-v1_zh.md"]],
  ["v-70452f7c","/zh/documents/connectors/redis/redis.html",{"t":"Redis connector"},["/zh/documents/connectors/redis/redis","/zh/documents/connectors/redis/redis.md"]],
  ["v-f4eee0ae","/zh/documents/connectors/redis/redis_zh.html",{"t":"Redis连接器"},["/zh/documents/connectors/redis/redis_zh","/zh/documents/connectors/redis/redis_zh.md"]],
  ["v-549caf37","/zh/documents/connectors/rocketmq/rocketmq-example.html",{"t":"RocketMQ connector examples"},["/zh/documents/connectors/rocketmq/rocketmq-example","/zh/documents/connectors/rocketmq/rocketmq-example.md"]],
  ["v-303c9be4","/zh/documents/connectors/rocketmq/rocketmq-example_zh.html",{"t":"RocketMQ连接器配置示例"},["/zh/documents/connectors/rocketmq/rocketmq-example_zh","/zh/documents/connectors/rocketmq/rocketmq-example_zh.md"]],
  ["v-c8e55698","/zh/documents/connectors/rocketmq/rocketmq.html",{"t":"RocketMQ connector"},["/zh/documents/connectors/rocketmq/rocketmq","/zh/documents/connectors/rocketmq/rocketmq.md"]],
  ["v-462bbf71","/zh/documents/connectors/rocketmq/rocketmq_zh.html",{"t":"RocketMQ连接器"},["/zh/documents/connectors/rocketmq/rocketmq_zh","/zh/documents/connectors/rocketmq/rocketmq_zh.md"]],
  ["v-3706649a","/404.html",{"t":""},["/404"]],
]
